import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ApolloWrapper from "./providers";
import CartProvider from "@/context/CartContext";
import UserProvider from "@/context/UserContext";
import FacetsProvider from "@/context/useFacet";
import { Toaster } from "sonner";
import LocalCartProvider from "@/context/LocalCartContext";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "SOLAR CABAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.variable} antialiased`}>
          <Toaster position="top-right" expand richColors closeButton />
          <ApolloWrapper>
            <UserProvider>
              <FacetsProvider>
                <LocalCartProvider>
                  <CartProvider>{children}</CartProvider>
                </LocalCartProvider>
              </FacetsProvider>
            </UserProvider>
          </ApolloWrapper>
          <div
            id="clerk-captcha"
            style={{
              position: "fixed",
              bottom: "20px",
              left: "20px",
              zIndex: 9999999,
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}