import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import ApolloWrapper from "./providers";
import CartProvider from "@/context/CartContext";
import UserProvider from "@/context/UserContext";
import FacetsProvider from "@/context/useFacet";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "SOLAR CABAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <ApolloWrapper>
          <UserProvider>
            <FacetsProvider>
              <CartProvider>{children}</CartProvider>
            </FacetsProvider>
          </UserProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
